### ISSUE TITLE
Create tables for each building

### ISSUE THREAD

**Issue by mohammadmehrab** [UTDallasEPICS/utd-oos-bottle-counter#137]
**Do this ticket AFTER a table UI is implemented, refer to **

Refer to [the Stonybrook website](https://www.stonybrook.edu/commcms/sustainability/Environmental/wbfsdashboard.php)

When we click on a building's pin on the map or a building's name on the main table to the left, an additional table pops up on the side that has the list of all water fountains, their location descriptions, and their bottle count.

We want to recreate this, so we need to implement

**Comment by KabirTapiawala** [comment]
![Image](https://github.com/user-attachments/assets/34699738-b73a-48e5-b1ee-ff22bce9004e)
