### ISSUE TITLE
Implement logic for adding coordinates to the prisma

### ISSUE THREAD

**Issue by btp220002** [UTDallasEPICS/utd-oos-bottle-counter#188]
REQUIRES BUILDING PRISMA TO BE CREATED (ISSUE #186)

**Comment by KabirTapiawala** [comment]
Added logic for longitude and latitude to add buildings, and a form to type that into the add building section. Verified working with sqlite: ![Image](https://github.com/user-attachments/assets/a8def502-5cee-456c-a20e-df9e3ebfea49)
